sonar.projectKey=DorjiOm_ICT932-SecureWebApp-DevSecOps
sonar.organization=dorjiom

sonar.sources=accounts,taskmanager,tasks
sonar.exclusions=**/migrations/**,**/venv/**,**/src/**,**/tests/**,**/*tests*.py,**/test_*.py

sonar.python.version=3.13
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml